import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import Provider from './provider/Provider'

const inter = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     <Provider>
     <body className={inter.className}>{children}</body>
     </Provider>
    </html>
  )
}
